backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{month}}-{{day}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "TÃ­tulo", name: "title", widget: "string"}
      - {label: "Publicado en", name: "date", widget: "datetime"}
      - {label: "Imagen de portada", name: "thumbnail", widget: "image"}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Clasificado en", name: "tags", widget: "string"}